# Generated by Django 4.2.4 on 2023-08-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdDoctor', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('DelayDoctor', models.TimeField()),
                ('EnterDoctor', models.TimeField()),
                ('HurryDoctor', models.TimeField()),
                ('ExitDoctor', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('IdDoctor', models.CharField(max_length=200)),
            ],
        ),
    ]
