# Generated by Django 4.2.4 on 2023-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='DateDoctor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
