# Generated by Django 4.2.4 on 2023-09-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_doctor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='DelayDoctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='EnterDoctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ExitDoctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='HurryDoctor',
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('DelayDoctor', models.TimeField(blank=True, null=True)),
                ('EnterDoctor', models.TimeField(blank=True, null=True)),
                ('HurryDoctor', models.TimeField(blank=True, null=True)),
                ('ExitDoctor', models.TimeField(blank=True, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.doctor')),
            ],
        ),
    ]
