# Generated by Django 4.2.4 on 2023-09-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_doctor_date_remove_doctor_delaydoctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Date',
        ),
        migrations.AddField(
            model_name='details',
            name='DateDoctor',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
